import random
characterSet = "abcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ@#"
userInput = int(input("Enter Length for Password to be Generated:-"))
generatedPassword = "".join(random.sample(characterSet, userInput))
print(generatedPassword)

# Here userInput is length of password given by the user
# characterSet has predefined characters from which password is generated
# Here random list is generated by random.sample(iterator,length) method, later that list is converted by string.join() method
